name: PR Add Remove Labels Based on user input
on:
  issue_comment:
    types: [created, edited, deleted]

permissions:
  pull-requests: write
  contents: write

jobs:
  add-remove-labels:
    if: |
      contains(github.event.comment.body, '/wip') ||
      contains(github.event.comment.body, '/verified') ||
      contains(github.event.comment.body, '/lgtm')

    runs-on: ubuntu-latest

    steps:
      - name: Acknowledge the request with thumbs up reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ github.event.comment.id }}
          reactions: '+1'

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Run size labeler
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_NUMBER: ${{ github.event.issue.number }}
          GITHUB_EVENT_ACTION: ${{ github.event.action }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: uv run python .github/workflows/scripts/pr_labeler.py
