name: Tox Tests

on:
  pull_request:

jobs:
  tox-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Install tox-uv
      run: |
        uv tool install tox --with tox-uv

    - name: Run tox environments
      run: |
        tox
